name: Build and Push Docker Image

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - add-new-files
  pull_request:
    branches:
      - add-new-files

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: pranjalkumar09
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t  pranjalkumar09/computer_vision_projects:latestt .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push  pranjalkumar09/computer_vision_projects:latest
